name: Java CI with Maven

on: [ push, pull_request ]

jobs:
  verify:
    runs-on: ubuntu-20.04
    name: Integration test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify